FROM golang:1.23.4-alpine as builder

# Copy application data into image
WORKDIR /app
COPY . /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Copy only `.go` files, if you want all files to be copied then replace `with `COPY . .` for the code below.
COPY *.go .

# Install our third-party application for hot-reloading capability.
RUN ["go", "get", "github.com/githubnemo/CompileDaemon"]
RUN ["go", "install", "github.com/githubnemo/CompileDaemon"]
EXPOSE 50051
ENTRYPOINT CompileDaemon -polling -log-prefix=false -build="go build ." -command="./todo-api" -directory="./"